version: '3.11'

services:
  postgres:
      image: postgres:15
      restart: always
      env_file:
        - .env
      volumes:
      - postgres_data:/var/lib/postgresql/data
      expose:
        - ${POSTGRES_PORT}
  django:
      build: ./Django_docker
      restart: always
      command: ["sh", "./entrypoint.sh"]
      volumes:
        - ./Django_docker/docker_web:/home/Django_docker/
        - static_volume:/home/Django_docker/static
      ports:
        - "8000:8000"
      expose:
        - 8000
      env_file:
        - .env
      user: "${UID}:${GID}"
      depends_on:
        - postgres
  nginx:
      build: ./Nginx
      restart: always
      volumes:
        - static_volume:/home/Django_docker/static
      ports:
        - "80:80"
      depends_on:
        - django

volumes:
  postgres_data:
  static_volume: